# Generated by Django 5.2 on 2025-05-06 05:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(blank=True, null=True)),
                ('tld', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None)),
                ('cca2', models.CharField(max_length=10, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=10, null=True)),
                ('cioc', models.CharField(blank=True, max_length=10, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('un_member', models.BooleanField(default=False)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('idd', models.JSONField(blank=True, null=True)),
                ('capital', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('alt_spellings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('region', models.CharField(max_length=100)),
                ('subregion', models.CharField(max_length=100)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('latlng', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, size=None)),
                ('landlocked', models.BooleanField(default=False)),
                ('borders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None)),
                ('area', models.FloatField()),
                ('demonyms', models.JSONField(blank=True, null=True)),
                ('cca3', models.CharField(max_length=15)),
                ('translations', models.JSONField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=15, null=True)),
                ('maps', models.JSONField(blank=True, null=True)),
                ('population', models.BigIntegerField()),
                ('gini', models.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=15, null=True)),
                ('car', models.JSONField(blank=True, null=True)),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('continents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('flags', models.JSONField(blank=True, null=True)),
                ('coat_of_arms', models.JSONField(blank=True, null=True)),
                ('start_of_week', models.CharField(blank=True, max_length=15, null=True)),
                ('capital_info', models.JSONField(blank=True, null=True)),
                ('postal_code', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
